### ISSUE TITLE
Definition of x,y,z

### ISSUE THREAD

**Issue by jora-blum** [pieye/nimbus-python#2]
The documents state that the values for x,y,z form a 3D point cloud. But x and y are themselves a 2D array and not a 1D vector. How can I get the 3D point cloud?

**Comment by Coimbra1984** [comment]
The 3D imager has a resolution of 352*286 active pixels. This shape is represented in the vector shape of x, y and z arrays.
Nevertheless the 3D point cloud are these x, y and z arrays. You can flatten the arrays, if you wish to (x.flatten(), y.flatten(), z.flatten())
