### ISSUE TITLE
C++ API?

### ISSUE THREAD

**Issue by robindarby** [pieye/nimbus-python#4]
Hello - can we get access to a/the C/C++ API?

**Comment by bjajoh** [comment]
Hi, yeah I'll prepare an example project. In the meantime all you need is mentioned [here](https://nimbus-docs.readthedocs.io/en/latest/usage/embedded.html#adding-a-custom-processing-stage).
But you need to be aware that the C++ API is directly integrated in the processing stage, therefore only available locally on the Pi.

**Comment by robindarby** [comment]
Perfect - thank you!

**Comment by bjajoh** [comment]
@robindarby In case you still need an example, here is a prepared cmake project which implements this interface. https://github.com/pieye/nimbus-c

**Comment by robindarby** [comment]
Fantastic, appreciate the work.
